import type { Diary, DiaryGoal } from "@/generated/prisma";

type ExampleDiary = Diary & { goals: DiaryGoal[] };

const example_entries: ExampleDiary[] = [
    {
        id: "diary-2024-W04",
        accountId: "83f11e35-a97e-4c21-bf9a-716a6f853889",
        entryTime: new Date(1741474800 * 1000),
        project: "printf",
        completionWeeks: 3,
        motivation: 8,
        learnings: "Learned about memory management and string manipulation in C",
        obstacles: "Struggling with proper memory allocation in ft_split",
        editableDiary: false,
        editableGoalCompletion: false,
        createTime: new Date(),
        updateTime: new Date(),
        goals: [
            {
                id: "goal-1",
                diaryId: "accounts/83f11e35-a97e-4c21-bf9a-716a6f853889/diaries/2024-W04",
                title: "Complete ft_split implementation",
                completed: false,
                createTime: new Date(),
                updateTime: new Date(),
            },
            {
                id: "goal-2",
                diaryId: "accounts/83f11e35-a97e-4c21-bf9a-716a6f853889/diaries/2024-W04",
                title: "Write tests for string functions",
                completed: true,
                createTime: new Date(),
                updateTime: new Date(),
            },
        ],
    },
    {
        id: "diary-2024-W03",
        accountId: "83f11e35-a97e-4c21-bf9a-716a6f853889",
        entryTime: new Date(1740870000 * 1000),
        project: "printf",
        completionWeeks: 4,
        motivation: 9,
        learnings: "Getting comfortable with pointers and memory allocation",
        obstacles: "Understanding linked list implementation",
        editableDiary: false,
        editableGoalCompletion: false,
        createTime: new Date(),
        updateTime: new Date(),
        goals: [
            {
                id: "goal-3",
                diaryId: "accounts/83f11e35-a97e-4c21-bf9a-716a6f853889/diaries/2024-W03",
                title: "Implement basic string functions",
                completed: true,
                createTime: new Date(),
                updateTime: new Date(),
            },
            {
                id: "goal-4",
                diaryId: "accounts/83f11e35-a97e-4c21-bf9a-716a6f853889/diaries/2024-W03",
                title: "Start working on memory functions",
                completed: true,
                createTime: new Date(),
                updateTime: new Date(),
            },
        ],
    },
    {
        id: "diary-2024-W02",
        accountId: "83f11e35-a97e-4c21-bf9a-716a6f853889",
        entryTime: new Date(1740265200 * 1000),
        project: "printf",
        completionWeeks: 5,
        motivation: 7,
        learnings: "Started learning C programming fundamentals",
        obstacles: "Adjusting to low-level programming concepts",
        editableDiary: false,
        editableGoalCompletion: false,
        createTime: new Date(),
        updateTime: new Date(),
        goals: [
            {
                id: "goal-5",
                diaryId: "accounts/83f11e35-a97e-4c21-bf9a-716a6f853889/diaries/2024-W02",
                title: "Set up development environment",
                completed: true,
                createTime: new Date(),
                updateTime: new Date(),
            },
            {
                id: "goal-6",
                diaryId: "accounts/83f11e35-a97e-4c21-bf9a-716a6f853889/diaries/2024-W02",
                title: "Complete first 5 functions",
                completed: true,
                createTime: new Date(),
                updateTime: new Date(),
            },
        ],
    },
    {
        id: "diary-2024-W01",
        accountId: "83f11e35-a97e-4c21-bf9a-716a6f853889",
        entryTime: new Date(1739660400 * 1000),
        project: "libft",
        completionWeeks: 1,
        motivation: 9,
        learnings: "Completed final libft exercises",
        obstacles: "Time management with multiple assignments",
        editableDiary: false,
        editableGoalCompletion: false,
        createTime: new Date(),
        updateTime: new Date(),
        goals: [
            {
                id: "goal-7",
                diaryId: "accounts/83f11e35-a97e-4c21-bf9a-716a6f853889/diaries/2024-W01",
                title: "Complete BSQ project",
                completed: true,
                createTime: new Date(),
                updateTime: new Date(),
            },
            {
                id: "goal-8",
                diaryId: "accounts/83f11e35-a97e-4c21-bf9a-716a6f853889/diaries/2024-W01",
                title: "Prepare for final exam",
                completed: true,
                createTime: new Date(),
                updateTime: new Date(),
            },
        ],
    },
    {
        id: "diary-2023-W52",
        accountId: "83f11e35-a97e-4c21-bf9a-716a6f853889",
        entryTime: new Date(1739055600 * 1000),
        project: "libft",
        completionWeeks: 2,
        motivation: 8,
        learnings: "Advanced C concepts and group projects",
        obstacles: "Complex pointer arithmetic in C",
        editableDiary: false,
        editableGoalCompletion: false,
        createTime: new Date(),
        updateTime: new Date(),
        goals: [
            {
                id: "goal-9",
                diaryId: "accounts/83f11e35-a97e-4c21-bf9a-716a6f853889/diaries/2023-W52",
                title: "Complete rush01 project",
                completed: true,
                createTime: new Date(),
                updateTime: new Date(),
            },
            {
                id: "goal-10",
                diaryId: "accounts/83f11e35-a97e-4c21-bf9a-716a6f853889/diaries/2023-W52",
                title: "Study for C09",
                completed: true,
                createTime: new Date(),
                updateTime: new Date(),
            },
        ],
    },
    {
        id: "diary-2023-W51",
        accountId: "83f11e35-a97e-4c21-bf9a-716a6f853889",
        entryTime: new Date(1738450800 * 1000),
        project: "libft",
        completionWeeks: 3,
        motivation: 6,
        learnings: "Shell scripting and basic C programming",
        obstacles: "Challenging rush00 weekend project",
        editableDiary: false,
        editableGoalCompletion: false,
        createTime: new Date(),
        updateTime: new Date(),
        goals: [
            {
                id: "goal-11",
                diaryId: "accounts/83f11e35-a97e-4c21-bf9a-716a6f853889/diaries/2023-W51",
                title: "Complete Shell01",
                completed: true,
                createTime: new Date(),
                updateTime: new Date(),
            },
            {
                id: "goal-12",
                diaryId: "accounts/83f11e35-a97e-4c21-bf9a-716a6f853889/diaries/2023-W51",
                title: "Start C03 exercises",
                completed: false,
                createTime: new Date(),
                updateTime: new Date(),
            },
        ],
    },
];

export default example_entries;
